Test
jiujianz/chat-space pull request #1
Opened 2019-01-26 07:55 UTC by jiujianz

# WIP
chat-spaceのデータベース設計

# WHY
データベースの設計の訓練

2019-01-27 02:03 UTC, kuroko918 requested changes
users、groupsテーブルも作成して下さい。

2019-01-27 02:03 UTC, kuroko918 commented on README.md
>  ### Accountsテーブル
これは何のテーブルですか？

2019-01-27 03:50 UTC, jiujianz commented on README.md
>  ### Accountsテーブル
usersテーブル、groupsテーブルの作成をしました。
usersテーブルに投稿したメッセージも関連させると思われますがbodyカラムとimageカラムだけで宜しいでしょうか？

```suggestion
### Accountsテーブル
```
これはusersテーブルのつもりでした。

2019-01-27 04:00 UTC, ghost requested changes

2019-01-27 04:00 UTC, hiroki5123 commented on README.md
>  ### associationテーブル
associationはテーブルではないです！

2019-01-27 04:02 UTC, ghost requested changes

2019-01-27 04:02 UTC, hiroki5123 commented on README.md
> +|user_id|integer|foreign_key: true
groupsテーブルに必要なカラムを見直してみましょう

2019-01-27 04:02 UTC, hiroki5123 commented on README.md
> +
Groupsテーブルのアソシエーションはどこに記述されていますか？

2019-01-27 06:29 UTC, jiujianz commented
Groupsテーブル、アソシエーション、共に改変いたしました。

2019-01-27 06:34 UTC, hiroki5123 commented
あまりアソシエーションやDB設計のカリキュラムの理解が浅いように思われますので今一度カリキュラムの復習をお願いいたします。

2019-01-27 08:15 UTC, jiujianz commented
何度も申し訳ございません、アソシエーションを理解し改善いたしました。

2019-01-27 08:19 UTC, kuroko918 commented on README.md
>  - belongs_to :user
groupとのアソシエーションが抜けています。

2019-01-27 08:19 UTC, kuroko918 commented on README.md
> +
userとのアソシエーションが抜けています。

2019-01-27 08:19 UTC, kuroko918 commented on README.md
> +|user_id|integer|foreign_key: true
こちらは必要ないかと思います。

2019-01-27 10:07 UTC, jiujianz commented
何度も有難うございます。訂正致しましたのでご確認お願い致します。

2019-01-27 10:15 UTC, kuroko918 commented
修正が反映されていません、確認お願いします！

2019-01-27 15:27 UTC, jiujianz commented
申し訳ございません、改善しました。

2019-01-28 02:00 UTC, takebn26 requested changes

2019-01-28 02:00 UTC, takebn26 commented on README.md
>  ### Membersテーブル
こちらは中間テーブルの命名規則に則ったほうがいいです！

2019-01-28 02:00 UTC, takebn26 commented on README.md
> +|body|text|null: false, foreign_key: true|
bodyとimageはどちらもnullになる場合があるので
`null: false` 外しておきましょう

2019-01-28 02:00 UTC, takebn26 commented on README.md
> +|time|timestamp|foreign_key: true|
こちらはrailsが自動的にいれるcreated_atを利用していくので
消してしまいましょう

2019-01-28 02:00 UTC, takebn26 commented on README.md
> +|name|char|null: false, unique: true|
sqlのchar型は確かにありますが、今回はrailsを使っていることもあり
railsの中のstring型を使っていきましょう
ちなみにsqlで型を書いておくとしたら
railsのstring型はsqlだとcharではなく、varchar(255)になります

2019-01-28 02:00 UTC, takebn26 commented on README.md
> +- has_many :members
多対多の関係なのでhas_many, throughを使いましょう

2019-01-28 02:00 UTC, takebn26 commented on README.md
> +|name|char|null: false, unique: true|
indexの有無も書いておくといいかと思います

2019-01-28 12:10 UTC, jiujianz commented
ご指摘頂きましたところは全て改善致しました。
よろしくお願い致します。

2019-01-28 12:16 UTC, takebn26 requested changes

2019-01-28 12:16 UTC, takebn26 commented on README.md
>  |group_id|integer|null: false, foreign_key: true|
こちら外部キーはいらないですが
body や image
は必要になります

コメントが指している範囲は言及がない場合は、
コメントがついているすぐ上の行だけです！

2019-01-28 12:16 UTC, takebn26 commented on README.md
>  |password|char|null: false, unique: true
こちらもstringに変えましょう

2019-01-28 12:16 UTC, takebn26 commented on README.md
nameのところstringに変えましょう

2019-01-28 12:22 UTC, jiujianz commented
細かいところも見落としのご指摘はないようにします。

2019-01-28 12:24 UTC, jiujianz commented
細かいところまで見れてませんでした。
チェックお願いします。

2019-01-28 12:29 UTC, takebn26 reviewed
一点修正後LGTMです！
修正後にマージして次に進んでください！
お疲れ様です！

2019-01-28 12:29 UTC, takebn26 commented on README.md
> +|body|text|null: false, foreign_key: true|
bodyとimageはnull: falseは必要ないので外しましょう

2019-01-28 12:31 UTC, merged

2019-01-28 12:37 UTC, takebn26 commented on README.md
> +|image|string|foreign_key: true|
すみません漏れていましたが両方ともforeign_keyではありません、、、

2019-01-28 13:00 UTC, jiujianz commented
foeign_keyではいけない理由は理解出来ました。bodyとimageは外部キーは無いからですよね？
ということはbodyとimageのオプションは空という事で宜しいですか？