Api training
jiujianz/chat-space pull request #5
Opened 2019-02-23 10:02 UTC by jiujianz

#what
API機能を実装する

#why
非同期通信でのビューの動きを見るため

2019-02-23 10:07 UTC, jiujianz commented
メッセージを投稿するとエラーがでます原因もわからないため、
１,新しいブランチを作成する
2,jsファイルを作成する
3,フォームが送信されたら、イベントが発火するようにする
4,2のイベントが発火したときにAjaxを使用して、messages#createが動くようにする
5,messages#createでメッセージを保存し、respond_toを使用してHTMLとJSONの場合で処理を分ける
6,jbuilderを使用して、作成したメッセージをJSON形式で返す
7,返ってきたJSONをdoneメソッドで受取り、HTMLを作成する
この時点までの評価お願いします。

2019-02-23 10:15 UTC, yuki-uchida commented
エラーの解決はまだでしょうか？
コネクトなどでご質問頂ければ解決できますので、ぜひそちらをご利用ください。

現在のコードではエラーが起きるんですよね？エラーが起きる状況でコードの評価をするのは難しいです。コードの中身は見た所矛盾はないので、書き方自体はあっていると思われますが、プルリク上で見える変更点以外のコードとも依存関係にあるはず(コントローラーの記述やモデルの設定など)なので、正しいかはわかりません

2019-02-23 10:16 UTC, yuki-uchida requested changes

2019-02-23 10:16 UTC, yuki-uchida commented on app/assets/javascripts/message.js
> +	function buildHTML(content){
buildHTMLでは、何をどうするのかがわかりづらいので、何のHTMLを作るかわかる名前の方がいいです

2019-02-23 10:16 UTC, yuki-uchida commented on app/assets/javascripts/message.js
> +        .done(function(data){
dataでは何を受け取っているのかわかりづらいため、変更しましょう

2019-02-28 11:17 UTC, jiujianz commented
buildHTML,daneタグの引数の名前共に変更しました

2019-03-01 08:01 UTC, yuki-uchida requested changes

2019-03-01 08:01 UTC, yuki-uchida commented on app/assets/javascripts/message.js
> +	function buildHTML(message){
buildHTMLでは、何をどうするのかがわかりづらいので、buildSendMessageHTMLとかいかがでしょうか

2019-03-01 08:01 UTC, yuki-uchida commented on app/assets/javascripts/message.js
> +        .done(function(data){
変更が確認できません。pushは忘れていないですか？

2019-03-01 08:12 UTC, jiujianz commented
buildhtml変更しました

2019-03-01 08:18 UTC, TOMARUMARU commented on app/assets/javascripts/message.js
> +        var x = (message.image) ? `<img src="${message.image}" >` :``;
変数名を変更してください

2019-03-01 08:25 UTC, jiujianz commented
buildHTMLの引数の変数名を変更しました

2019-03-01 08:27 UTC, TOMARUMARU commented on app/assets/javascripts/message.js
> +        var x = (message.image) ? `<img src="${message.image}" >` :``;
こちら修正されていません

2019-03-02 05:59 UTC, jiujianz commented on app/assets/javascripts/message.js
> +        var x = (message.image) ? `<img src="${message.image}" >` :``;
https://github.com/jiujianz/chat-space/pull/5#discussion_r259574161

こちらで変数名の指摘があったので、変更したのですがこれではダメですか？

2019-03-02 06:06 UTC, TOMARUMARU commented
buildSendMessageHTML は関数、messageは引数です。
変数名は```x```ですね...

2019-03-02 06:11 UTC, jiujianz commented
勘違いしておりました。
ご指摘ありがとうございます。

2019-03-02 06:33 UTC, b-i-hide reviewed
コメントしました！
こちらの動作確認はできているでしょうか？？
動作していれば、gifなどで貼っていただけるとこちらも確認できるので、お願いします。

2019-03-02 06:33 UTC, b-i-hide commented on app/controllers/groups_controller.rb
> +    end
このへんのインデントが崩れているのが気になりますねぇ 🤔

2019-03-02 06:33 UTC, b-i-hide commented on app/assets/javascripts/message.js
> +})
改行入れましょう！

2019-03-02 06:43 UTC, jiujianz commented on app/assets/javascripts/message.js
> +})
改行入れました

2019-03-02 06:44 UTC, jiujianz commented on app/controllers/groups_controller.rb
> +    end
https://gyazo.com/7b8dc3fe72d6318f9b43a35f11aeecec
インデントですがエディッターで確認するとこんな感じですがgithubに反映された物では崩れていますか？

2019-03-02 06:44 UTC, jiujianz commented on app/controllers/groups_controller.rb
> +    end
https://gyazo.com/799dfa4255691df22a6df643c8b592ab
こちら動画です

2019-03-02 06:50 UTC, b-i-hide reviewed
細かいですが、コメントしました！
あとちょっとがんばりましょう〜！

2019-03-02 06:50 UTC, b-i-hide commented on app/controllers/groups_controller.rb
> +    end
おーなるほど！
おそらくこれはgithub側の問題ですね〜！
ありがとうございます〜！

2019-03-02 06:50 UTC, b-i-hide commented on app/assets/javascripts/message.js
> +        var api_message = (message.image) ? `<img src="${message.image}" >` :``;
ここってインデントレベルが同じで大丈夫ですか？

2019-03-02 06:50 UTC, b-i-hide commented on app/controllers/messages_controller.rb
> +		  respond_to do |format|
この辺もインデント崩れてますが、エディタだとうまくできてるやーつですか？

2019-03-02 06:53 UTC, jiujianz commented on app/assets/javascripts/message.js
> +        var api_message = (message.image) ? `<img src="${message.image}" >` :``;
https://gyazo.com/a79ef296c45db5cd88a21eecb73da207
こんな感じです

2019-03-02 06:55 UTC, jiujianz commented on app/controllers/messages_controller.rb
> +		  respond_to do |format|
https://gyazo.com/a4f4a214788c19e0f3e488b2babd41c6
こんな感じです

2019-03-02 06:58 UTC, b-i-hide commented
全体的には良さそうですね！
あとは非同期にメッセージを投稿できているかのgifを貼っていただいて、動作を確認させてください〜！

2019-03-02 07:03 UTC, jiujianz commented
https://gyazo.com/bf52a4188228ea0467df69a4d716409e
これで証明できてますか？

2019-03-02 07:09 UTC, b-i-hide commented
LGTMです〜！

2019-03-02 07:09 UTC, merged