自動更新機能の実装
jiujianz/chat-space pull request #8
Opened 2019-03-07 12:52 UTC by jiujianz

# WIP
自動更新機能を実装する

# WHY
定期的に非同期通信を行いグループのメッセージを取得しリロードの手間を省くため

2019-03-08 07:44 UTC, jiujianz commented
https://gyazo.com/2468c09a025bb38acf83b0ce0a538eb1
こちらが動画となっています。

2019-03-08 07:50 UTC, yuki-uchida requested changes

2019-03-08 07:50 UTC, yuki-uchida commented on app/assets/javascripts/message.js
> +	function GroupsMessageHTML(message){
GroupsMessageHTMLという単語、少し理解が難しいと思います。
あくまでグループのメッセージのHTMLとしか解釈できないので、グループのメッセージのHTMLをどうするの？
という観点から書いた方でいいです。作るのか削除するのか追加するのか変更するのか

2019-03-08 07:50 UTC, yuki-uchida commented on app/assets/javascripts/message.js
> +  function update(){
updateも何をupdateするのかわかるように書きましょう

2019-03-08 07:50 UTC, yuki-uchida commented on app/assets/javascripts/message.js
> +    .always(function(group_message){
group_messageとは何でしょう？
そのグループで発せられているメッセージを全てとってきているのでしょうか？それとも一部とってきているのでしょうか？

2019-03-08 07:50 UTC, yuki-uchida commented on app/assets/javascripts/message.js
>          .done(function(user_message){
user_messageも単語として解釈が難しいです

2019-03-08 08:13 UTC, jiujianz commented
ご指摘頂きました変数名は変更致しました。

2019-03-08 08:19 UTC, yuki-uchida requested changes
難しいとは思いますが、変数名・関数名は過不足なく説明できるような名前を検討しましょう

2019-03-08 08:19 UTC, yuki-uchida commented on app/assets/javascripts/message.js
> +	function DisplayAllMessages(message){
これはallMessagesですか？

2019-03-08 08:19 UTC, yuki-uchida commented on app/assets/javascripts/message.js
> +	function DisplayAllMessages(message){
また、displayという名前にするのであれば、この関数名の意味は全てのメッセージを表示するという意味になりますが、この関数内で「表示する」までやってますか？

HTMLを作るところまでではないですか？

2019-03-08 08:19 UTC, yuki-uchida commented on app/assets/javascripts/message.js
> +  function UpdateOtherUsersMessage(){
UpdateOtherUsersMessage
であれば、他のユーザーのメッセージをupdateするという解釈でいいですか？
あくまでupdateするのは「メッセージの表示」ではないですか？

2019-03-08 08:19 UTC, yuki-uchida commented on app/assets/javascripts/message.js
> +    .always(function(anotherUserSend_message){
anotherは他の一人という意味になりますが、
自分ではない一人が送信したmessageという解釈になります。
new_messagesとかでいいのではないでしょうか

2019-03-08 08:24 UTC, jiujianz commented on app/assets/javascripts/message.js
> +	function DisplayAllMessages(message){
HTMLを作るということは表示すると同義だと勘違いしてしまっていました

2019-03-08 08:27 UTC, jiujianz commented on app/assets/javascripts/message.js
> +  function UpdateOtherUsersMessage(){
はい、これは完全な把握漏れでした

2019-03-08 08:28 UTC, jiujianz commented on app/assets/javascripts/message.js
> +    .always(function(anotherUserSend_message){
英語の細かい意味の違いを勉強出来てませんでした。

2019-03-08 08:34 UTC, jiujianz commented
全体的に変数名のつけ方をわかっていませんでした。
記述内容からもたらされる影響に対する変数名を付けていたので純粋にその記述内容の変数名を付けるよにしていきます。ご指摘有難うございました。

2019-03-09 06:15 UTC, yuki-uchida requested changes

2019-03-09 06:15 UTC, yuki-uchida commented on app/assets/javascripts/message.js
> +	function AllMessagesHTML(message){
これは全てのMessageのHTMLという意味になりますが、この関数がすることは、Message一件分のHTMLを組み立てることのように思います。
なので、buildMessageHTMLといった名前のままで良いと思います。

2019-03-09 06:15 UTC, yuki-uchida commented on app/assets/javascripts/message.js
> +  function UpdateMessageDisplay(){
良いと思います

2019-03-09 06:19 UTC, jiujianz commented on app/assets/javascripts/message.js
> +	function AllMessagesHTML(message){
畏まりました。
有難うございます。

2019-03-09 06:21 UTC, yuki-uchida approved these changes
LGTMです。お疲れ様でした

2019-03-09 06:22 UTC, merged